name: Deploy to AWS S3

on:
  push:
    branches: [main] # Deploy only on pushes to main

jobs:
  deploy:
    name: S3 Upload Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify AWS CLI is available
        run: aws --version # Ensures CLI is installed

      - name: Debug script and public folder
        run: |
          echo "Listing deploy script:"
          ls -la ./deploy-aws.sh
          echo "Listing public folder:"
          ls -la ./public
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_DEPLOY_BUCKET: ${{ secrets.AWS_DEPLOY_BUCKET }}

      - name: Make deploy script executable
        run: chmod +x deploy-aws.sh

      - name: Deploy to AWS S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_DEPLOY_BUCKET: ${{ secrets.AWS_DEPLOY_BUCKET }}
        run: ./deploy-aws.sh
